# Generated by Django 2.0.3 on 2018-04-29 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra', models.IntegerField(verbose_name='ra')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_disciplina', models.CharField(max_length=100, verbose_name='nome')),
                ('ano', models.PositiveSmallIntegerField(verbose_name='ano')),
                ('semestre', models.PositiveSmallIntegerField(verbose_name='semestre')),
                ('sequencial', models.PositiveSmallIntegerField(verbose_name='sequencial')),
                ('data', models.DateField(verbose_name='data')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('ementa', models.TextField(verbose_name='ementa')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaOfertada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_disciplina', models.CharField(max_length=100, verbose_name='nome')),
                ('ano', models.PositiveSmallIntegerField(verbose_name='ano')),
                ('semestre', models.PositiveSmallIntegerField(verbose_name='semestre')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra_aluno', models.IntegerField(verbose_name='ra')),
                ('nome_disciplina', models.CharField(max_length=100, verbose_name='nome')),
                ('ano', models.PositiveSmallIntegerField(verbose_name='ano')),
                ('semestre', models.PositiveSmallIntegerField(verbose_name='semestre')),
            ],
        ),
    ]
