# Generated by Django 2.0.3 on 2018-04-29 02:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoAtividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra_aluno', models.IntegerField(verbose_name='ra')),
                ('nome_disciplina', models.CharField(max_length=100, verbose_name='nome')),
                ('ano', models.PositiveSmallIntegerField(verbose_name='ano')),
                ('semestre', models.PositiveSmallIntegerField(verbose_name='semestre')),
                ('sequencial', models.PositiveSmallIntegerField(verbose_name='sequencial')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='nota')),
            ],
        ),
        migrations.AddField(
            model_name='atividade',
            name='titulo',
            field=models.CharField(default=django.utils.timezone.now, max_length=150, verbose_name='titulo'),
            preserve_default=False,
        ),
    ]
