# Generated by Django 2.0.3 on 2018-04-29 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_auto_20180428_2355'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlunoAtividade',
        ),
        migrations.DeleteModel(
            name='Atividade',
        ),
        migrations.DeleteModel(
            name='Disciplina',
        ),
        migrations.DeleteModel(
            name='DisciplinaOfertada',
        ),
        migrations.DeleteModel(
            name='Matricula',
        ),
    ]
