# Generated by Django 2.0.3 on 2018-04-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('ementa', models.TextField(verbose_name='ementa')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaOfertada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_disciplina', models.CharField(max_length=100, verbose_name='nome')),
                ('ano', models.PositiveSmallIntegerField(verbose_name='ano')),
                ('semestre', models.PositiveSmallIntegerField(verbose_name='semestre')),
            ],
        ),
    ]
