# Generated by Django 2.0.3 on 2018-04-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeAtividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra_atividade', models.IntegerField(verbose_name='ra')),
                ('nome_disciplina', models.CharField(max_length=100, verbose_name='nome')),
                ('ano', models.PositiveSmallIntegerField(verbose_name='ano')),
                ('semestre', models.PositiveSmallIntegerField(verbose_name='semestre')),
                ('sequencial', models.PositiveSmallIntegerField(verbose_name='sequencial')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='nota')),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_disciplina', models.CharField(max_length=100, verbose_name='nome')),
                ('ano', models.PositiveSmallIntegerField(verbose_name='ano')),
                ('semestre', models.PositiveSmallIntegerField(verbose_name='semestre')),
                ('sequencial', models.PositiveSmallIntegerField(verbose_name='sequencial')),
                ('titulo', models.CharField(max_length=150, verbose_name='titulo')),
                ('data', models.DateField(verbose_name='data')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra_atividade', models.IntegerField(verbose_name='ra')),
                ('nome_disciplina', models.CharField(max_length=100, verbose_name='nome')),
                ('ano', models.PositiveSmallIntegerField(verbose_name='ano')),
                ('semestre', models.PositiveSmallIntegerField(verbose_name='semestre')),
            ],
        ),
    ]
